if (document.body.clientWidth<767) {     
  $("#msg").hide();
document.writeln("<style>");
document.writeln(".msgtb{overflow:hidden; float:left; width:100%;}");
document.writeln(".hx{float:left; margin:16px 5px 0px 0px; color:#e41f1f;}");
document.writeln(".bx{float:left; margin:9px 5px 0px 0px; color:#FFF;}");
document.writeln(".msgtb input,.msgtb select{height:30px;line-height:30px;border:1px solid #ccc;border-radius:3px;float:left;margin:6px 0px;width:94.5%;padding-left:6px;}");
document.writeln(".msgtb select{color:#a1a1a1;padding-left:6px;width: 94.5%;}");
document.writeln(".cttxt{border:1px solid #ccc;border-radius:4px;height:55px;width:94.5%;padding-left:4px;font-family:Arial, Helvetica, sans-serif;font-size:14px; margin:6px 0px;float:left;}");
document.writeln(".iqbtn input{height:25px; background:#fc3343; color:#ffffff; cursor:pointer;line-height:25px;border:0px;font-size:14px; margin-left:11px;margin-bottom:21px;} ");
document.writeln(".msgtb p{padding:0px !important; margin:0px !important;}");
document.writeln("</style>");
document.writeln("");
document.writeln("");
document.writeln("    <div class=\"msgtb\">");
document.writeln("  <form action=\"https://data.break-day.com/post_do.php\" method=\"post\" onsubmit=\"return chkInquiry()\" id=\"lmForm\" name=\"lmForm\">");
document.writeln("    <p class=\"clearfix\"><span class=\"hx\">*</span><input type=\"text\" name=\"name\" id=\"textn\" placeholder=\"Your Name:\"></p>");
document.writeln("    <p class=\"clearfix\"><span class=\"hx\">*</span><input type=\"text\" name=\"tel\" id=\"tel\" placeholder=\"Tel\"></p>");
document.writeln("    <p class=\"clearfix\"><span class=\"hx\">*</span><input type=\"text\" name=\"email\" id=\"gemail\" placeholder=\"Your Email Adress:\"></p>");
document.writeln("     <p class=\"clearfix\"><span class=\"hx\">*</span>");
document.writeln("      <select name=\"product\" id=\"product2\">");
document.writeln("      <option  selected=\"selected\" value=\"Select Equipment\" >Select Equipment</option>");
document.writeln("	  <option value=\"Mobile Crushers\">Mobile Crushers</option>");
document.writeln("	  <option value=\"Stationary Crushers\">Stationary Crushers</option>");
document.writeln("	  <option value=\"Sand Making Machines\">Sand Making Machines</option>");
document.writeln("      <option value=\"Grinding Mill\">Grinding Mill</option>");
document.writeln("      <option value=\"Beneficiation Machine\">Beneficiation Machine</option>");
document.writeln("      <option value=\"Other\">Other</option></select></p>");
document.writeln("     <p class=\"clearfix\"><span class=\"hx\">*</span>");
document.writeln("      <select name=\"message\" id=\"product3\">");
document.writeln("      <option selected=\"selected\" value=\"Select Capacity\" >Select Capacity</option>");
document.writeln("	  <option value=\"Capacity:800-1000(t/h)\">800-1000(t/h)</option>");
document.writeln("      <option value=\"Capacity:500-800(t/h)\">500-800(t/h)</option>");
document.writeln("      <option value=\"Capacity:300-500(t/h)\">300-500(t/h)</option>");
document.writeln("      <option value=\"Capacity:100-300(t/h)\">100-300(t/h)</option>");
document.writeln("      <option value=\"Capacity:30-100(t/h)\">30-100(t/h)</option>");
document.writeln("      <option value=\"Capacity:Other\">Other</option></select></p>");
document.writeln("      <p class=\"clearfix\"><span class=\"hx\">*</span>");
document.writeln("      <select name=\"message\" id=\"marerial\">");
document.writeln("      <option selected=\"selected\" value=\"Select Material\" >Select Material</option>");
document.writeln("	  <option value=\"Material:Granite\">Granite</option>");
document.writeln("	  <option value=\"Material:Limestone\">Limestone</option>");
document.writeln("	  <option value=\"Material:Basalt\">Basalt</option>");
document.writeln("      <option value=\"Material:Pebble\">Pebble </option>");
document.writeln("      <option value=\"Material:Gravel\">Gravel</option>");
document.writeln("	  <option value=\"Material:Gypsum\">Gypsum</option>");
document.writeln("	  <option value=\"Material:Barite\">Barite</option>");
document.writeln("	  <option value=\"Material:Quartz\">Quartz</option>");
document.writeln("      <option value=\"Material:Dolomite\">Dolomite </option>");
document.writeln("      <option value=\"Material:Gold Ore\">Gold Ore</option>");
document.writeln("      <option value=\"Material:Other\">Other</option></select></p>");
document.writeln("	  <p class=\"clearfix\"><span class=\"bx\">*</span><textarea name=\"message\" id=\"textc\" class=\"cttxt\" placeholder=\"Enter details: Raw material, Capacity, Feeding material size, Final product size, etc.\"></textarea></p>");
document.writeln("      <input name=\"url\" id=\"url\" type=\"hidden\" value=\"\">");
document.writeln("      <input name=\"lang\" value=\"en\" type=\"hidden\">");
document.writeln("      <p class=\"iqbtn\"><input type=\"submit\" value=\"ORDER NOW\"></p>");
document.writeln("  </form>");
document.writeln("    </div>");
document.writeln("<script>");
document.writeln("      function $g(obj){return document.getElementById(obj);}");
document.writeln("");
document.writeln("function chkInquiry(){");
document.writeln("	if($g(\"textn\").value==\"\"){alert(\"Please input your Name ! \");$g(\"textn\").focus();return false;}");
document.writeln("	if($g(\"tel\").value==\"\"){alert(\"Please input your Tel ! \");$g(\"tel\").focus();return false;}");
document.writeln("	if($g(\"gemail\").value==\"\"){alert(\"Please input your E-Mail ! \");$g(\"gemail\").focus();return false;}");
document.writeln("	");
document.writeln("	var check=document.lmForm.gemail.value;");
document.writeln(" 	if( check.indexOf(\"@\",0) == -1 ){     ");
document.writeln("    	alert(\"Please input a valid email address!\");");
document.writeln("		return false;}");
document.writeln("		");
document.writeln("	if($(\"#product2\").find(\"option:selected\").text()==\"Select Equipment\"){alert(\"Please Select Equipment ! \");$g(\"product2\").focus();return false;}");
document.writeln("	if($(\"#product3\").find(\"option:selected\").text()==\"Select Capacity\"){alert(\"Please Select Capacity ! \");$g(\"product3\").focus();return false;}");
document.writeln("	if($(\"#marerial\").find(\"option:selected\").text()==\"Select Material\"){alert(\"Please Select Material ! \");$g(\"marerial\").focus();return false;}");
document.writeln("	");
document.writeln("}");
document.getElementById("url").value=window.location.href;
document.writeln("</script>");
document.writeln("");

}